# Auto-generated by local_sysroot_configure
# System compiler and sysroot information detected at configure time

local_sysroot_info = struct(
    # Path to the system compiler used for detection
    compiler = %{compiler},

    # Compiler version string
    compiler_version = %{compiler_version},

    # C++ builtin include directories for cxx_builtin_include_directories
    # Includes both absolute paths (/usr/include/...) and sysroot-relative paths (/include/...)
    include_directories = %{include_directories},
)

# Deprecated: Use local_sysroot_info.include_directories instead
SYSTEM_INCLUDE_PATHS = local_sysroot_info.include_directories
