"""Repository rule to detect system compiler include paths for local sysroot."""

load(
    "//gpu:compiler_common_tools.bzl",
    "get_cxx_inc_directories",
    "to_list_of_strings",
)

def _find_system_compiler(repository_ctx):
    """Find the system C++ compiler.

    Tries to find a system compiler in order: cc, c++, gcc, g++, clang, clang++

    Args:
        repository_ctx: The repository context.

    Returns:
        Path to the system compiler, or None if not found.
    """
    # Try common compiler names in order of preference
    for compiler in ["cc", "c++", "gcc", "g++", "clang", "clang++"]:
        result = repository_ctx.which(compiler)
        if result:
            return str(result)
    return None

def _local_sysroot_configure_impl(repository_ctx):
    """Implementation of local_sysroot_configure repository rule.

    Detects system compiler and include paths, generates a .bzl file with the info.
    """
    # Find system compiler
    cc = _find_system_compiler(repository_ctx)
    if not cc:
        fail("Could not find system compiler (tried: cc, c++, gcc, g++, clang, clang++)")

    # Get C++ include directories using existing detection logic
    # Pass None for tf_sys_root since we want system paths, not custom sysroot
    include_dirs = get_cxx_inc_directories(repository_ctx, cc, None)

    # Add sysroot-relative paths for --sysroot=/
    # When using --sysroot=/, paths like /include/c++/9 are relative to the sysroot
    # So we need both /usr/include/c++/9 (absolute) and /include/c++/9 (sysroot-relative)
    all_include_dirs = []
    for inc in include_dirs:
        all_include_dirs.append(inc)
        # Add sysroot-relative version: /usr/... -> /...
        if inc.startswith("/usr/"):
            relative = inc.replace("/usr/", "/", 1)
            if relative not in all_include_dirs:
                all_include_dirs.append(relative)

    # Get compiler version
    version_result = repository_ctx.execute([cc, "--version"])
    compiler_version = version_result.stdout.split("\n")[0] if version_result.return_code == 0 else "unknown"

    # Generate defs.bzl from template
    repository_ctx.template(
        "defs.bzl",
        repository_ctx.attr._defs_template,
        substitutions = {
            "%{compiler}": repr(cc),
            "%{compiler_version}": repr(compiler_version),
            "%{include_directories}": str(all_include_dirs),
        },
        executable = False,
    )

    # Create a minimal BUILD file
    repository_ctx.file(
        "BUILD",
        content = """# Auto-generated by local_sysroot_configure

package(default_visibility = ["//visibility:public"])
""",
        executable = False,
    )

local_sysroot_configure = repository_rule(
    implementation = _local_sysroot_configure_impl,
    local = True,
    configure = True,
    attrs = {
        "_defs_template": attr.label(
            default = Label("//cc/sysroots:defs.bzl.tpl"),
            allow_single_file = True,
        ),
    },
    doc = """
Detects system compiler include paths for use with local sysroot.

This repository rule finds the system C++ compiler and queries it for
default include directories. These paths are used in cxx_builtin_include_directories
when --sysroot=/ is used for local (non-hermetic) sysroot compilation.

The rule tries to find a compiler in this order: cc, c++, gcc, g++, clang, clang++
It then runs the compiler with -E -xc++ to detect include paths, similar to
how Bazel's cc_configure works.

The detected paths are written to local_sysroot_paths.bzl and can be loaded
in BUILD files.
""",
)
