# Auto-generated by local_clang_configure
# Clang path: %{compiler_path}
# Version: %{version}

local_clang_info = struct(
    # Whether clang was found
    found = %{found},

    # Path to the clang compiler
    compiler_path = %{compiler_path},

    # Clang resource directory (from -print-resource-dir)
    resource_dir = %{resource_dir},

    # Clang builtin include directory (resource_dir/include)
    include_dir = %{include_dir},

    # Clang version string
    version = %{version},

    # C++ builtin include directories
    include_directories = %{include_directories},
)

# Deprecated: Use local_clang_info instead
def local_clang():
    """Returns the local clang compiler configuration."""
    return local_clang_info
