"""Repository rule for detecting local clang installation.

This rule detects the local clang compiler and its configuration,
making it available for toolchains that need to use system clang.

Usage in WORKSPACE:
    local_clang_configure(name = "local_config_clang")

Then in BUILD files:
    load("@local_config_clang//:clang.bzl", "local_clang")
    # local_clang.compiler_path, local_clang.include_dir, etc.
"""

load(
    "//common:common.bzl",
    "execute",
    "get_host_environ",
    "which",
)
load(
    "//gpu:compiler_common_tools.bzl",
    "get_cxx_inc_directories",
)

_CLANG_COMPILER_PATH = "CLANG_COMPILER_PATH"

def _find_clang(repository_ctx):
    """Find the clang compiler path."""
    clang_path = get_host_environ(repository_ctx, _CLANG_COMPILER_PATH)
    if clang_path:
        if clang_path.startswith("/"):
            return clang_path

        # Try to find it in PATH
        found = which(repository_ctx, clang_path)
        if found:
            return found

    return None

def _get_clang_resource_dir(repository_ctx, clang_path):
    """Get clang resource directory using -print-resource-dir."""
    result = execute(repository_ctx, [clang_path, "-print-resource-dir"])
    if result.return_code == 0:
        return result.stdout.strip()
    return ""

def _get_clang_version(repository_ctx, clang_path):
    """Get clang version."""
    result = execute(repository_ctx, [clang_path, "--version"])
    if result.return_code == 0:
        # Parse "clang version X.Y.Z" or "Ubuntu clang version X.Y.Z"
        for line in result.stdout.split("\n"):
            if "clang version" in line.lower():
                parts = line.split(" ")
                for i, part in enumerate(parts):
                    if part == "version" and i + 1 < len(parts):
                        return parts[i + 1]
    return ""

def _local_clang_configure_impl(repository_ctx):
    """Implementation of local_clang_configure repository rule."""

    clang_path = _find_clang(repository_ctx)

    if not clang_path:
        # Clang not found - generate empty configuration
        substitutions = {
            "%{found}": "False",
            "%{compiler_path}": '""',
            "%{resource_dir}": '""',
            "%{include_dir}": '""',
            "%{version}": '""',
            "%{include_directories}": "[]",
        }
    else:
        # Clang found - detect configuration
        resource_dir = _get_clang_resource_dir(repository_ctx, clang_path)
        version = _get_clang_version(repository_ctx, clang_path)
        include_dir = resource_dir + "/include" if resource_dir else ""

        # Get all include directories
        tf_sysroot = get_host_environ(repository_ctx, "TF_SYSROOT", "")
        include_directories = get_cxx_inc_directories(
            repository_ctx,
            clang_path,
            tf_sysroot,
        )

        # Ensure clang resource include directory is present (contains stddef.h, stdint.h, etc.)
        # Always prepend it to ensure it's first in the search path, removing any duplicate
        if include_dir:
            include_directories = [d for d in include_directories if d != include_dir]
            include_directories = [include_dir] + include_directories

        substitutions = {
            "%{found}": "True",
            "%{compiler_path}": '"{}"'.format(clang_path),
            "%{resource_dir}": '"{}"'.format(resource_dir),
            "%{include_dir}": '"{}"'.format(include_dir),
            "%{version}": '"{}"'.format(version),
            "%{include_directories}": repr(include_directories),
        }

    # Generate clang.bzl from template
    repository_ctx.template(
        "clang.bzl",
        Label("//cc/llvms/local:clang_info.bzl.tpl"),
        substitutions = substitutions,
    )

    # Generate BUILD file
    repository_ctx.file("BUILD", """
# Auto-generated by local_clang_configure

package(default_visibility = ["//visibility:public"])

# Expose clang configuration for other rules to use
exports_files(["clang.bzl"])
""")

local_clang_configure = repository_rule(
    implementation = _local_clang_configure_impl,
    environ = [
        _CLANG_COMPILER_PATH,
        "TF_SYSROOT",
        "PATH",
    ],
    local = True,
)
