load(
    "@rules_cc//cc:defs.bzl",
    "cc_import",
    "cc_library",
    "cc_test",
)

cc_library(
    name = "utils_lib",
    srcs = ["utils.cc"],
    hdrs = ["utils.h"],
    features = ["header_modules"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "basic_test",
    srcs = ["basic_test.cc"],
    features = ["use_header_modules"],
    deps = [
        ":utils_lib",
        "@gtest//:gtest_main",
    ],
)
