#!/bin/bash

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# allow passing the output of one command as input to the next
set -o pipefail

PARAMS_FILE="${1#@}"

LINKER_NAME=$(sed -n 's/^-l:\(ld-.*\.so.*\)/\1/p' "$PARAMS_FILE" | head -n 1)
SOLIB_PATH=$(sed -n 's/^-Wl,-rpath,\$ORIGIN\/\([^/]*_solib[^/]*toolchain[^/]*\).*/\1/p' "$PARAMS_FILE" | head -n 1)

if [[ -n "$LINKER_NAME" && -n "$SOLIB_PATH" ]]; then
  DYNAMIC_LINKER_PATH="${SOLIB_PATH}/${LINKER_NAME}"
  echo "DYNAMIC_LINKER_PATH=$DYNAMIC_LINKER_PATH"

  $GCC_PATH $@ -Wl,--dynamic-linker=$DYNAMIC_LINKER_PATH
else
  $GCC_PATH $@
fi

