#!/bin/bash

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# allow passing the output of one command as input to the next
set -o pipefail

PARAMS_FILE="${1#@}"

if [[ -n "$PARAMS_FILE" && "$PARAMS_FILE" == *.params ]]; then
    ARGS=("$@")

    LOADER_FILE=$(sed -n 's/^-l:\(ld-.*\.so.*\)/\1/p' "$PARAMS_FILE" | head -n 1)

    if [[ -n "$LOADER_FILE" ]]; then
        FULL_DIRS=$(sed -n 's/^-L\(.*_solib_[^[:space:]]*\)/\1/p' "$PARAMS_FILE" | sort -u)

        for FULL_DIR in $FULL_DIRS; do
            if [[ -f "${FULL_DIR}/${LOADER_FILE}" ]]; then
                REL_DIR=$(echo "$FULL_DIR" | sed -n 's|^.*bazel-out/[^/]*/bin/\(_solib_.*\)|\1|p')
                LOADER_PATH="${REL_DIR}/${LOADER_FILE}"

                ARGS+=("-Wl,--dynamic-linker=$LOADER_PATH")
                echo "Successfully injected dynamic linker: $LOADER_PATH"
                break
            fi
        done
    fi
    exec "$GCC_PATH" "${ARGS[@]}"
else
    $GCC_PATH $@
fi
