# Automatically perform a release whenever a new "release-like" tag is pushed to the repo.
name: Release

on:
  push:
    tags:
      # Detect tags that look like a release.
      # Note that we don't use a "v" prefix to help anchor this pattern.
      # This is purely a matter of preference.
      - "*.*.*"

jobs:
  release:
    permissions:
      id-token: write
      attestations: write
      contents: write
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@a841d62420f41a87a601fb331f3c2c2cc088506e # v7.2.3
    with:
      prerelease: false
      release_files: rules_ml_toolchain-*.tar.gz
      tag_name: ${{ github.ref_name }}
      bazel_test_command: bazel test --config=bzlmod //cc/tests/cpu:all
  publish:
    permissions:
      id-token: write
      contents: read
    needs: release
    uses: ./.github/workflows/publish.yaml
    with:
      tag_name: ${{ github.ref_name }}
      environment: release
    secrets:
      # Necessary to push to the BCR fork, and to open a pull request against a registry
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
